version: '3.8'
services:
  society-scribe:
    build:
      context: .
      dockerfile: Dockerfile
      target: application
    image: pf2e-society-scribe:latest

    # 👇 enable GPU for this service
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

      # your existing env…
      - CAMPAIGN_NAME=${CAMPAIGN_NAME:-default}
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - MODEL_NAME=${MODEL_NAME:-qwen-instruct}

    ports:
      - "${PORT:-8000}:8000"

    volumes:
      - ${HOME}/pf2e-campaigns/campaigns/${CAMPAIGN_NAME:-default}:/app/campaign-data
      - ${HOME}/pf2e-campaigns/shared/pf2e.db:/app/data/pf2e.db:ro
      - ${HOME}/pf2e-campaigns/shared/models:/app/models:ro

    # (Optional) extra Compose GPU compatibility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    restart: unless-stopped
    networks: [pf2e-network]

networks:
  pf2e-network:
    driver: bridge
    name: pf2e-network
